language: "node_js"
os: "linux"
dist: "xenial"

node_js:
  - 12.13.0
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script: yarn run test:ci
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.2
  - export PATH=$HOME/.yarn/bin:$PATH
before_deploy: yarn run build && yarn run docs
deploy:
  - provider: npm
    skip_cleanup: true
    email: golodhros@gmail.com
    api_token: $NPM_TOKEN
    on:
      tags: true
      repo: britecharts/britecharts
  - provider: pages
    skip_cleanup: true
    strategy: git
    token: $GITHUB_TOKEN
    local_dir: docs
    on:
      branch: master

