# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: NPM Publish

on:
  release:
    types: [created]

jobs:
  getNodeVersion:
    uses: calyptia/.github/.github/workflows/get_node_version.yml@main

  build:
    runs-on: ubuntu-latest
    needs: getNodeVersion
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setting node version to ${{ needs.getNodeVersion.outputs.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: '${{ needs.getNodeVersion.outputs.node_version }}'
      - name: Install and Test
        uses: borales/actions-yarn@v2.0.2
        with:
          cmd: install
      - name: Build ğŸ”§
        uses: borales/actions-yarn@v2.0.2
        with:
          cmd: run build
      - uses: borales/actions-yarn@v2.0.2
        with:
          cmd: run docs

  publish-npm:
    needs: [getNodeVersion, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
      - name: Setting node version to ${{ needs.getNodeVersion.outputs.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: '${{ needs.getNodeVersion.outputs.node_version }}'
          registry-url: https://registry.npmjs.org/
      - uses: borales/actions-yarn@v2.0.2
        with:
          cmd: install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  deploy-docs:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs








