# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: NPM Publish

on:
  release:
    types: [created]

jobs:
  getNodeVersion:
    uses: calyptia/.github/.github/workflows/get_node_version.yml@main

  build:
    runs-on: ubuntu-latest
    needs: getNodeVersion
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setting node version to ${{ needs.getNodeVersion.outputs.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: '${{ needs.getNodeVersion.outputs.node_version }}'
      - name: Install
        run: yarn
      - name: Build ğŸ”§
        run: yarn build
      - name: Docs ğŸ“š
        run: yarn docs

  publish-npm:
    needs: [getNodeVersion, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
      - name: Setting node version to ${{ needs.getNodeVersion.outputs.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: '${{ needs.getNodeVersion.outputs.node_version }}'
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  deploy-docs:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
