name: Storybook Deployment to Chromatic

# Event for the workflow
on: push

# List of jobs
jobs:
  getNodeVersion:
    uses: calyptia/.github/.github/workflows/get_node_version.yml@main

  chromatic-deployment:
    name: Deploy to Chromatic
    runs-on: ubuntu-latest
    needs: getNodeVersion
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setting node version to ${{ needs.getNodeVersion.outputs.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: '${{ needs.getNodeVersion.outputs.node_version }}'

      - name: Use Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '.yarn/cache'
          key: ${{ runner.os }}-yarn-${{ needs.getNodeVersion.outputs.node_version }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn
      - name: Build all packages ğŸ”§
        run: yarn build 
      - name: build core storybook ğŸ”§
        run: yarn workspace @britecharts/core demo:build
      - name: Publish core storybook to Chromatic ğŸš€
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          projectToken: ${{ secrets.CHROMATIC_TOKEN_CORE }}
          autoAcceptChanges: 'main'
          storybookBuildDir: './packages/core/dist/storybook'
      - name: build react storybook ğŸ”§
        run: yarn workspace @britecharts/react demo:build
      - name: Publish react storybook to Chromatic ğŸš€
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          projectToken: ${{ secrets.CHROMATIC_TOKEN_REACT }}
          autoAcceptChanges: 'main'
          storybookBuildDir: './packages/react/dist/storybook'
      - name: build main storybook ğŸ”§
        run: yarn workspace @britecharts/demos build
      - name: Publish main storybook to Chromatic ğŸš€
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: 'main'
          storybookBuildDir: './packages/demos/dist'