---
jobs:
  tests:
    name: node ${{ matrix.node-version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Yarn ğŸ“¦
        run: npm i -g yarn@1.22.5
      - name: Install Dependencies â¬
        run: yarn --frozen-lockfile
      - name: Build Library ğŸ”§
        run: yarn build
      - name: Generate Docs ğŸ“ƒ
        run: yarn run docs
      - name: Linting Styles ğŸŒˆ
        run: yarn lint:styles
      - name: Linting Code ğŸ—ƒ
        run: yarn lint:js
      - name: Testing Library ğŸ•µï¸â€â™€ï¸
        run: yarn test:ci
    strategy:
      matrix:
        node-version:
          - 14.x
        os:
          - ubuntu-latest
name: tests
'on':
  - push
  - pull_request
