name: Test Docs Deployment

on:
  pull_request:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  getNodeVersion:
    uses: calyptia/.github/.github/workflows/get_node_version.yml@main

  test-deploy:
    name: Test docs deployment
    runs-on: ubuntu-latest
    needs: getNodeVersion
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
      - name: Setting node version to ${{ needs.getNodeVersion.outputs.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: '${{ needs.getNodeVersion.outputs.node_version }}'
      - name: Use Yarn cache ğŸ”§
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '.yarn/cache'
          key: ${{ runner.os }}-yarn-${{ needs.getNodeVersion.outputs.node_version }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn
      - name: Build docs website ğŸ“š
        run: yarn docs:build