name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  getNodeVersion:
    uses: gagoar/ts-node-template/.github/workflows/get_node_version.yml@main

  unit-test:
    runs-on: ubuntu-latest
    needs: getNodeVersion
    steps:
      - uses: actions/checkout@main
      - name: Setting node version to ${{ needs.getNodeVersion.outputs.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: '${{ needs.getNodeVersion.outputs.node_version }}'
      - name: Use Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '.yarn/cache'
          key: ${{ runner.os }}-yarn-${{ needs.getNodeVersion.outputs.node_version }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn
      - name: Testing Library üïµÔ∏è‚Äç‚ôÄÔ∏è
        run: yarn test:ci
      - name: Send coverage to codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
